-- MySQL Script generated by MySQL Workbench
-- Tue Oct 22 19:35:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Użytkownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Użytkownik` (
  `idUżytkownik` INT NOT NULL,
  `Imię` NVARCHAR(45) NULL,
  `Nazwisko` NVARCHAR(45) NULL,
  `Hasło` NVARCHAR(45) NULL,
  `Nr_tel` INT NULL,
  PRIMARY KEY (`idUżytkownik`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Miasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Miasto` (
  `idMiasto` INT NOT NULL,
  `Nazwa` NVARCHAR(45) NULL,
  `Kraj` NVARCHAR(50) NULL,
  PRIMARY KEY (`idMiasto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sala` (
  `idSala` INT NOT NULL,
  `Nazwa` NVARCHAR(45) NULL,
  `Adres` NVARCHAR(45) NULL,
  `Miasto_idMiasto` INT NOT NULL,
  PRIMARY KEY (`idSala`, `Miasto_idMiasto`),
  INDEX `fk_Sala_Miasto1_idx` (`Miasto_idMiasto` ASC) VISIBLE,
  CONSTRAINT `fk_Sala_Miasto1`
    FOREIGN KEY (`Miasto_idMiasto`)
    REFERENCES `mydb`.`Miasto` (`idMiasto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rabat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rabat` (
  `idRabat` INT NOT NULL,
  `Kod` NVARCHAR(45) NULL,
  PRIMARY KEY (`idRabat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rezerwacja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rezerwacja` (
  `idRezerwacja` INT NOT NULL,
  `RezerwacjaStart` DATETIME NULL,
  `RezerwacjaKoniec` DATETIME NULL,
  `Sala_idSala` INT NOT NULL,
  `Rabat_idRabat` INT NOT NULL,
  `Użytkownik_idUżytkownik` INT NOT NULL,
  PRIMARY KEY (`idRezerwacja`, `Sala_idSala`, `Rabat_idRabat`, `Użytkownik_idUżytkownik`),
  INDEX `fk_Rezerwacja_Sala_idx` (`Sala_idSala` ASC) VISIBLE,
  INDEX `fk_Rezerwacja_Rabat1_idx` (`Rabat_idRabat` ASC) VISIBLE,
  INDEX `fk_Rezerwacja_Użytkownik1_idx` (`Użytkownik_idUżytkownik` ASC) VISIBLE,
  CONSTRAINT `fk_Rezerwacja_Sala`
    FOREIGN KEY (`Sala_idSala`)
    REFERENCES `mydb`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rezerwacja_Rabat1`
    FOREIGN KEY (`Rabat_idRabat`)
    REFERENCES `mydb`.`Rabat` (`idRabat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rezerwacja_Użytkownik1`
    FOREIGN KEY (`Użytkownik_idUżytkownik`)
    REFERENCES `mydb`.`Użytkownik` (`idUżytkownik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
